from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """Data validation model for incoming chat requests."""
    message: str = Field(..., description="The customer message to send to the customer support system.")

class ChatResponse(BaseModel):
    """Structured response schema sent back to the frontend."""
    success: bool = Field(..., description="Indicates if the request completed successfully.")
    response: str = Field(..., description="The reply content generated by the Customer Support system.")
    source: str = Field(..., description="The resource generating the answer (e.g. 'lemma-workflow').")
    timestamp: datetime = Field(..., description="UTC timestamp of when the response was returned.")
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Flexible key-value storage for future-proofing and diagnostics (e.g. run_id, conversation_id)."
    )
